# Generated by Django 4.1.7 on 2024-08-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
