# Generated by Django 4.2.16 on 2025-02-06 12:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_delete_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 300], upload_to='cause'),
        ),
    ]
