# Generated by Django 5.1.6 on 2025-02-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='charity.profile'),
            preserve_default=False,
        ),
    ]
