# Generated by Django 5.1.6 on 2025-02-08 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_remove_project_user_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 12, 43, 24, 211714, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
