# Generated by Django 5.1.6 on 2025-02-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(),
        ),
    ]
