# Generated by Django 5.1.6 on 2025-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_alter_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
