# Generated by Django 5.1.6 on 2025-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
