# Generated by Django 5.1.6 on 2025-02-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_project_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_raised',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
