# Generated by Django 5.1.6 on 2025-02-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0013_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='project',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='charity.project'),
            preserve_default=False,
        ),
    ]
