# Generated by Django 5.1.6 on 2025-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0014_volunteer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cac_certificate',
            field=models.FileField(default='media/events/SmartSelect_20240210_131049_Chrome.jpeg', upload_to='cac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cac_number',
            field=models.CharField(default='345657gh', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='scuml',
            field=models.FileField(default='media/events/SmartSelect_20240210_131049_Chrome.jpeg', upload_to='scuml'),
            preserve_default=False,
        ),
    ]
