# Generated by Django 5.1.6 on 2025-02-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0015_profile_cac_certificate_profile_cac_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('resources_needed', models.TextField()),
                ('personnel_needed', models.PositiveIntegerField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.project')),
            ],
        ),
    ]
