# Generated by Django 5.1.6 on 2025-02-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0016_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='ngos_in_collaboration_with',
            field=models.ManyToManyField(to='charity.profile'),
        ),
    ]
