# Generated by Django 5.1.6 on 2025-02-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0017_collaboration_ngos_in_collaboration_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='personnel_needed',
            field=models.TextField(),
        ),
    ]
