# Generated by Django 5.1.6 on 2025-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0019_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=40),
        ),
    ]
