# Generated by Django 5.1.6 on 2025-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0020_alter_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.CharField(default='access bank', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_name',
            field=models.CharField(default='sabeel', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_number',
            field=models.CharField(default='1234567890', max_length=10),
            preserve_default=False,
        ),
    ]
