# Generated by Django 5.1.6 on 2025-02-16 12:20

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0021_profile_bank_profile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.collaboration')),
            ],
        ),
    ]
