# Generated by Django 5.1.6 on 2025-02-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0022_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='role',
            field=models.CharField(default='doctor', max_length=30),
            preserve_default=False,
        ),
    ]
