# Generated by Django 5.1.6 on 2025-02-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0023_personnel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(default='Education', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_category',
            field=models.CharField(default='good education', max_length=50),
            preserve_default=False,
        ),
    ]
