# Generated by Django 5.1.6 on 2025-02-16 14:40

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0024_profile_category_profile_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='charity/static/images/contact.jpg', force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 300], upload_to='profiles'),
            preserve_default=False,
        ),
    ]
