# Generated by Django 5.1.6 on 2025-02-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0025_profile_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_category',
            field=models.TextField(),
        ),
    ]
