# Generated by Django 5.1.6 on 2025-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0027_profile_category_2_profile_category_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_category_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_category_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_category_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_category_5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_category_6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_category_7',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_category_8',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_category_9',
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_category',
            field=models.TextField(),
        ),
    ]
