# Generated by Django 5.1.6 on 2025-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0028_remove_profile_category_2_remove_profile_category_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sub_account_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_account_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
