# Generated by Django 5.1.6 on 2025-02-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0029_payment_sub_account_id_profile_sub_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.project'),
        ),
    ]
