# Generated by Django 5.1.6 on 2025-02-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0030_payment_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
